version: "3.7"

services:
  flask:
    build: ./flask_app
    container_name: flask
    restart: always
    volumes:
      - ./flask_app:/app/
    environment:
      - APP_NAME=MYFlaskApp
    env_file:
      - flask_app/.env
    expose:
      - 8080
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 5002:80
  react_app_metodos:
    build: ./react_app
    container_name: react_app_metodos
    restart: always
    volumes:
      - "./react_app:/react_app"
    ports:
      - 3000:3000
